branch-defaults:
  default:
    environment: django-env
global:
  application_name: test_form
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.4 (Preconfigured - Docker)
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
